Fix AssertionError: View function mapping...
When using the current file for the solution, I get the following error:

```
Traceback (most recent call last):
  File "project.py", line 32, in <module>
    @app.route('/restaurants/<int:restaurant_id>/')
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: restaurantMenu
```

The issue is caused by the file having two restaurantMenu function defs. I corrected this by using the def made in Quiz: Templates Quiz (Lesson 3-10).

This file would still fail when accessing the root of the site. Since we don't access it anymore at this part of the lesson, and the lesson makes no mention of how to refactor it properly anyway, I figured I won't bother fixing. :)